name: Trigger Whiff Watch API Daily

on:
  schedule:
    - cron: '0 14 * * *'  # 9 AM Central Time (14:00 UTC)
  workflow_dispatch:

jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Whiff Watcher API endpoint
        run: curl -s https://whiff-watcher-api.onrender.com/api/whiff-watch
